services:
  girlscape:
    environment:
      - NODE_ENV=development
    container_name: girlscape
    image: floramoon/girlscape:latest
    restart: unless-stopped
    volumes:
      - .env:/usr/src/app/.env
      - ./src:/usr/src/app/src
      - ./node_modules:/usr/src/app/node_modules
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    user: "1000:1000"
    volumes:
      - ./data/:/data
